### ISSUE TITLE
Preprocessing code about eyediap dataset

### ISSUE THREAD

**Issue by ackness** [aliabid2243/data-fusion-based-gaze-estimation#1]
Hi,
Thanks for your codes. 
I have a problem, you seem to have changed part of preprocessing codes of [ReccurentGaze](https://github.com/crisie/RecurrentGaze/blob/master/generate_training_FT.py#L301), so I have no idea about the content of face_feats_xxx.h5. Can you share this part of codes?

Best,
Yong

**Comment by abalikhan** [comment]
@ackness, I have done several experiments and these are some of the results of previous experiences, you can either forget that part and save the files separately or wait till I fix them and update the correct version.
Thank you.
